apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: kong-on-eks
  region: us-east-2

nodeGroups:
  - name: main
    instanceType: m5.large
    desiredCapacity: 2
    ssh:
      allow: false
